plugins { id 'com.android.application' }

android {
    namespace 'ir.amnayar.app'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.amnayar.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
